FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN apk add --no-cache ffmpeg

RUN cp /usr/bin/ffmpeg ./

COPY index3.js .

EXPOSE 8002
EXPOSE 1937

CMD ["node", "index3.js"]